on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

name: WordPress Autofixer

jobs:
  phpcbf-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: cs2pr, composer

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-dev

      # Check the code-style consistency of the PHP files.
      - name: Fix PHP code style
        id: codestyle
        continue-on-error: true
        run: ./vendor/squizlabs/php_codesniffer/bin/phpcbf . --standard=./phpcs.xml

      - name: Get Branch Names
        id: branch
        uses: tj-actions/branch-names@v5.1

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          commit-message: PHPCBF Auto Fix
          committer: Linchpin Bot <dev@linchpin.com>
          signoff: false
          branch: ${{ steps.branch.outputs.current_branch }}-phpcbf
          delete-branch: true
          title: 'Auto Fix Formatting'
          body: |
            Update Code Formatting
          labels: |
            phpcs
            automated pr
